export const sampleData = [
  {
    id: 1,
    shortlink: "https://linkly.com/Bn41aCOlnxj",
    original_link: "https://www.youtube.com/",
    QrCode: "/qr.png",
    clicks: 113,
    status: "Active",
    statusIcon: "/active.svg",
    date: "Oct-09-2024",
  },
  {
    id: 2,
    shortlink: "https://linkly.com/ABC123",
    original_link: "https://www.example.com/",
    QrCode: "/qr.png",
    clicks: 78,
    status: "Inactive",
    statusIcon: "/inactive.svg",
    date: "Oct-08-2024",
  },
  {
    id: 3,
    shortlink: "https://linkly.com/XYZ789",
    original_link: "https://www.google.com/",
    QrCode: "/qr.png",
    clicks: 205,
    status: "Active",
    statusIcon: "/active.svg",
    date: "Oct-07-2024",
  },
  {
    id: 4,
    shortlink: "https://linkly.com/DEF456",
    original_link: "https://www.amazon.com/",
    QrCode: "/qr.png",
    clicks: 42,
    status: "Inactive",
    statusIcon: "/inactive.svg",
    date: "Oct-06-2024",
  },
  {
    id: 5,
    shortlink: "https://linkly.com/GHI789",
    original_link: "https://www.netflix.com/",
    QrCode: "/qr.png",
    clicks: 321,
    status: "Active",
    statusIcon: "/active.svg",
    date: "Oct-05-2024",
  },
];
